<?php
/**
 * Multiple Intelligence Test - 80 Questions
 * Categories: 1-Verbal, 2-Logic, 3-Visual, 4-Kinesthetic, 5-Musical, 6-Interpersonal, 7-Intrapersonal, 8-Naturalist
 */

if (!defined('ABSPATH')) exit;

return array(
    // Format: array('question_text', intelligence_category, sort_order)
    array('Aud cuvintele în minte înainte de a le rosti, citi sau scrie.', 1, 1),
    array('Oamenii vin la mine să ceară sfaturi, atât la locul de muncă cât și acasă.', 6, 2),
    array('Petrec timp în mod regulat meditând, reflectând și gândindu-mă la problemele importante ale vieții.', 7, 3),
    array('Îmi place să fiu înconjurat de plante.', 8, 4),
    array('Când am o problemă caut ajutorul altcuiva mai degrabă decât să încerc s-o rezolv singur.', 6, 5),
    array('Prefer cărțile/periodicele cu ilustrații multe.', 3, 6),
    array('Am o voce plăcută.', 5, 7),
    array('Prefer sporturile de echipă decât care se practică individual.', 6, 8),
    array('Trebuie să exersez pentru a-mi forma o deprindere; nu ajunge doar să citesc sau să urmăresc o demonstrație.', 4, 9),
    array('Aud întotdeauna o notă falsă.', 5, 10),
    array('Mă simt mai bine când lucrurile sunt măsurate, clasificate, analizate, cuantificate.', 2, 11),
    array('Adesea mă joc cu animalele.', 8, 12),
    array('Cred că am o coordonare motrică bună.', 4, 13),
    array('Adesea bat ritmul sau fredonez când lucrez sau învăț ceva nou.', 5, 14),
    array('Cărțile sunt foarte importante pentru mine.', 1, 15),
    array('Am participat la sesiuni și seminarii de consiliere și dezvoltare personală ca să aflu mai multe despre mine însumi/însămi.', 7, 16),
    array('Când închid ochii, văd adesea imagini clare.', 3, 17),
    array('Am cel puțin trei prieteni apropiați.', 6, 18),
    array('Rețin mai mult de la radio sau ascultând o casetă audio decât de la TV sau din filme.', 1, 19),
    array('Îmi place să găsesc erori de logică în ceea ce spun sau fac ceilalți.', 2, 20),
    array('Țin un jurnal în care consemnez evenimentele din viața mea interioară.', 7, 21),
    array('Îmi plac jocurile ca Scrabble, anagramele etc.', 1, 22),
    array('Știu multe melodii.', 5, 23),
    array('Sunt patron sau cel puțin m-am gândit serios să încep o afacere proprie.', 7, 24),
    array('Prefer să-mi petrec serile cu prietenii decât să stau acasă singur.', 6, 25),
    array('Pot să-mi imaginez ușor cum ar arăta ceva văzut de sus.', 3, 26),
    array('Dacă aud o melodie o dată sau de două ori, pot s-o reproduc cu acuratețe.', 5, 27),
    array('Fac experimente cu plante și animale.', 8, 28),
    array('Fac sport/activități fizice în mod regulat.', 4, 29),
    array('Îmi place să mă distrez, pe mine și pe alții, cu rime sau jocuri de cuvinte.', 1, 30),
    array('Mă consider lider (sau alții mi-au spus că sunt lider).', 6, 31),
    array('Sunt sensibil la culori.', 3, 32),
    array('Mi-e greu să stau nemișcat mai mult timp.', 4, 33),
    array('Pot să socotesc în minte cu ușurință.', 2, 34),
    array('Când lucrez îmi place să categorisesc lucrurile după importanța lor.', 8, 35),
    array('Consider că am voință puternică și că sunt independent(ă).', 7, 36),
    array('Matematica și științele au fost materiile mele preferate în școală.', 2, 37),
    array('Pot să țin ritmul cu un instrument de percuție simplu când se cântă un cântec.', 5, 38),
    array('Folosesc frecvent un aparat de fotografiat sau o cameră video pentru a înregistra ceea ce văd în jur.', 3, 39),
    array('Ceilalți îmi cer câteodată să explic sensul cuvintelor pe care le folosesc când scriu sau când vorbesc.', 1, 40),
    array('Îmi place să port haine din materiale naturale.', 8, 41),
    array('Sunt realist în privința punctelor mele tari și slabe (datorită feedback-ului primit din diverse surse).', 7, 42),
    array('Cele mai multe idei îmi vin când mă plimb, fac jogging sau desfășor o activitate fizică.', 4, 43),
    array('Îmi place să mă joc cu jocuri de puzzle, labirint și alte jocuri vizuale.', 3, 44),
    array('Prefer să joc Monopoly sau bridge decât să joc jocuri video, sau să joc alte jocuri de unul singur.', 6, 45),
    array('Ascult frecvent muzică la radio, casetofon etc.', 5, 46),
    array('Visez mult noaptea.', 3, 47),
    array('Ca elev, am învățat mai ușor la engleză, științele sociale și istorie decât la matematică și științe.', 1, 48),
    array('Prefer să petrec un week-end singur la o cabană în pădure decât într-o stațiune modernă cu multă lume în jur.', 7, 49),
    array('Îmi place să cos, să țes, să cioplesc, să fac tâmplărie sau alte activități manual.', 4, 50),
    array('Câteodată mă surprind mergând pe stradă fredonând.', 5, 51),
    array('Mă orientez ușor în locuri necunoscute.', 3, 52),
    array('Când conduc pe autostradă sunt mai atent la ce scrie pe panouri decât la peisaj.', 1, 53),
    array('Mă simt bine în pădure.', 8, 54),
    array('Îmi place să joc jocuri care necesită gândire logică.', 2, 55),
    array('Îmi place să-i învăț pe alții (indivizi sau grupuri) ceea ce știu eu ce fac.', 6, 56),
    array('Simt nevoia să ating obiectele pentru a afla mai multe despre ele.', 4, 57),
    array('Îmi place să desenez sau să măzgălesc.', 3, 58),
    array('Îmi place să mă implic în activități legate de munca mea, biserică sau comunitate, care presupun prezența unui număr mare de oameni.', 6, 59),
    array('Îmi place să fac mici experimente (ex. "Ce-ar fi dacă aș dubla cantitatea de apă pe care o torn la rădăcina trandafirului în fiecare săptămână?").', 2, 60),
    array('Pot să răspund la atacuri cu argument.', 7, 61),
    array('Cânt la un instrument muzical.', 5, 62),
    array('La școală, geometria mi s-a părut mai ușoară decât algebra.', 3, 63),
    array('Mintea mea caută structuri, regularități, secvențe logice în jur.', 2, 64),
    array('Recent am scris ceva ce m-a făcut să mă simt mândru sau a fost apreciat de ceilalți.', 1, 65),
    array('Weekend-ul ideal este o ieșire în natură.', 8, 66),
    array('Mă simt bine în mijlocul mulțimii.', 6, 67),
    array('Cred că aproape orice are o explicație rațională.', 2, 68),
    array('Am un hobby pe care nu-l dezvălui altora.', 7, 69),
    array('Prefer să-mi petrec timpul liber în natură.', 4, 70),
    array('Mă interesează progresele din știință.', 2, 71),
    array('Sunt foarte bun bucătar.', 8, 72),
    array('Folosesc frecvent gesturi sau alte forme de limbaj corporal când vorbesc cu alții.', 4, 73),
    array('Viața mea ar fi mai săracă dacă n-ar fi muzica.', 5, 74),
    array('Uneori gândesc în concepte clare, abstracte, pe care nu le formulez în cuvinte sau în imagini.', 2, 75),
    array('Conversația mea face apel frecvent la lucruri pe care le-am citit sau le-am auzit.', 1, 76),
    array('Am câteva scopuri importante în viață, la care mă gândesc în mod regulat.', 7, 77),
    array('În camera mea trebuie să fie o floare.', 8, 78),
    array('Îmi place "Montagne russe" și alte experiențe fizice asemănătoare.', 4, 79),
    array('Am mulți prieteni.', 6, 80)
);